name: Generate Output Channels

on:
  push:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Java
        run: sudo apt update && sudo apt install -y default-jdk

      - name: Build generator
        run: |
          cd java_tools
          ./gradlew :console_launcher:shadowJar

      - name: Run generator
        run: |
          java -cp java_tools/console_launcher/build/libs/console_launcher-all.jar \
          com.rusefi.output.TsOutput \
          firmware/console/output_channels.txt \
          firmware/live_data_generated/output_channels_generated

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: output-headers
          path: firmware/live_data_generated/
