name: Generate firmware files for uaefi

on:
 # push:
  #  branches: [ engine_hours ]
  workflow_dispatch:

jobs:
  generate-uaefi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix mtools zip unzip build-essential

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make scripts executable
        run: chmod +x firmware/gen_config.sh

      - name: Generate config for uaefi
        run: |
          cd firmware
          ./gen_config.sh uaefi

      - name: Check if output header was created
        run: |
          ls -l firmware/live_data_generated/output_channels_generated.h
          grep engine_hours firmware/live_data_generated/output_channels_generated.h || echo "No engine_hours fields found"
