name: List Gradle Tasks for config_definition

on:
  push:
  workflow_dispatch:

jobs:
  list-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: List config_definition Gradle Tasks
        run: |
          cd java_tools
          ./gradlew :config_definition:tasks --all
