name: Firmware Build with Output Generation

on:
  push:
    branches:
      - engine_hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi \
            openjdk-17-jdk python3 python3-pip mtools dosfstools

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build firmware (includes output file generation)
        run: |
          export PATH=$PATH:/usr/lib/ccache
          ./gradlew :firmware:build

      - name: Upload output_channels_generated.h
        uses: actions/upload-artifact@v4
        with:
          name: output_headers
          path: firmware/live_data_generated/output_channels_generated.h
