name: Generate Output Channels

on:
  push:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build code generators
        run: |
          cd java_tools
          ./gradlew :config_definition:shadowJar

      - name: Generate output headers
        run: |
          cd java_tools
          ./gradlew generate

      - name: Upload generated files
        uses: actions/upload-artifact@v4
        with:
          name: generated-headers
          path: firmware/live_data_generated/
