name: Generate Output Channels

on:
  push:
  workflow_dispatch:

  

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y default-jdk

      - name: Build code generator
        run: |
          cd java_tools
          ./gradlew :config_definition:shadowJar
          
      - name: Find all JAR files
        run: |
          find . -name "*.jar" | grep config_definition || true



      - name: Generate output channels
        run: |
          cd firmware
          java -cp ../java_tools/config_definition/build/libs/config_definition-all.jar \
          com.rusefi.output.OutputConfigurationConsumer \
          config/boards/hellen/uaefi/generated_engine.txt \
          live_data_generated/generated_engine \
          config/boards/hellen/uaefi/generated_engine.java
          
      - name: Upload generated headers
        uses: actions/upload-artifact@v4
        with:
          name: generated-output-channels
          path: firmware/live_data_generated/
