name: Generate Output Channels

on:
  push:
  workflow_dispatch:

  

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y default-jdk

      - name: Build code generator
        run: |
          cd java_tools
          ./gradlew :config_definition:shadowJar
          
      #- name: Generate output channels
       # run: |
        #  cd java_tools
         # ./gradlew :config_definition:shadowJar
          #cd ../firmware
          #java -cp ../java_tools/config_definition/build/libs/config_definition-all.jar com.rusefi.output.OutputsSectionConsumer
      - name: Generate output channels
        run: |
          ./java_tools/gradlew -p java_tools :config_definition:shadowJar
          java -cp java_tools/configuration_definition/build/libs/config_definition-all.jar \
          com.rusefi.output.OutputsSectionConsumer \
          firmware/console/binary/output_channels.txt \
          firmware/live_data_generated/output_channels_generated.h

          
      - name: Upload generated headers
        uses: actions/upload-artifact@v4
        with:
          name: generated-output-channels
          path: firmware/live_data_generated/
