name: Generate-Autogen-Files
on:
  #push:
   # branches: [ engine_hours ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Java (use Java 17, which rusEFI uses for Gradle build)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build the ConfigDefinition tool (Gradle shadowJar)
      - name: Build config_definition JAR
        working-directory: java_tools
        run: ./gradlew :config_definition:shadowJar

      # Run the configuration generation script to regenerate headers and ini files
      - name: Run config generation
        working-directory: firmware
        run: bash ./gen_config.sh

      # (Optional) Verify if any files changed as a result of generation
      - name: Check for changes
        run: |
          if git status --porcelain | grep -q "firmware/"; then
            echo "⚠️ Auto-generated files were updated.";
            # Optionally, you could add steps here to commit or upload the changed files
          else
            echo "No changes in auto-generated files.";
          fi
